name: CI

on:
  push:
  pull_request:

env:
  VERBOSE: 1

jobs:
  build-base:
    name: Test on Ubuntu with gcc
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Linux dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get -q -y install meson ninja-build libntl-dev libboost-test-dev libssl-dev
    - name: Build and test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose

  build-flags:
    name: Test on ${{ matrix.cfg.os }} with ${{ matrix.cfg.compiler }}
    needs: [build-base]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { os: ubuntu-22.04, compiler: gcc, cxxcompiler: g++, ld: bfd } # = gcc-11
        - { os: ubuntu-22.04, compiler: clang, cxxcompiler: clang++, ld: lld } # = clang-14
        - { os: ubuntu-22.04, compiler: gcc-12, cxxcompiler: g++-12, ld: bfd }
        - { os: ubuntu-22.04, compiler: clang-13, cxxcompiler: clang++-13, ld: lld-13 }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Linux dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get -q -y install ${{ matrix.cfg.compiler }} meson ninja-build libntl-dev libboost-test-dev libssl-dev
        sudo apt-get -q -y install ${{ matrix.cfg.cxxcompiler }} || true
        sudo apt-get -q -y install ${{ matrix.cfg.ld }} || true
    - name: Build and test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose
        meson-version: 0.56
      env:
        CC: ${{ matrix.cfg.compiler }}
        CXX: ${{ matrix.cfg.cxxcompiler }}
        CC_LD: ${{ matrix.cfg.ld }}
        CXX_LD: ${{ matrix.cfg.ld }}

  build-flags-macos:
    name: Test on macOS
    needs: [build-base]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install dependencies
      run: |
        brew upgrade python@3 || true
        brew install ninja meson openssl@3 boost
    - name: Build and test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose
        meson-version: 0.56

  build-flags-windows:
    name: Test on Windows with MSVC
    needs: [build-base]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Windows SDK
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install meson and ninja
      run:
        pip install meson ninja
    - name: Build and test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        setup-options: --vsenv
        options: --verbose
        meson-version: 0.56
