name: NIST submission package

on:
  push:

env:
  VERBOSE: 1

jobs:
  build:
    name: Build submission package
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Linux dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get -q -y install meson ninja-build
    - name: Build
      run: |
        mkdir build
        cd build
        meson .. -DEM-128=disabled
        ninja prepare_nist
    - name: Upload NIST submission package
      uses: actions/upload-artifact@v3
      with:
        name: faest-submission-package
        path: build/submission/

